name: ydtrader-high-concurrency
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - openjdk=17
  - pip
  - curl
  - unzip
  - uv
  - pip:
      - ./vendor/wheels/pyyd-1.486.96.99-cp39-cp39-linux_x86_64.whl
