#!/usr/bin/env python3
"""Compile the protected ydcore modules in place with Cython."""

import argparse
import shutil
from pathlib import Path

from Cython.Build import cythonize
from setuptools import Extension, setup


PROJECT_ROOT = Path(__file__).resolve().parents[1]
CORE_MODULES = (
    "licensing",
    "launcher",
    "trading",
    "monitoring",
    "marketdata",
    "_public_key",
)


def embed_public_key(public_key):
    target = PROJECT_ROOT / "ydcore" / "_public_key.py"
    pem = public_key.read_bytes()
    target.write_text(
        "# Generated by build_tools/build_cython.py; never hand-edit.\n"
        f"PUBLIC_KEY_PEM = {pem!r}\n",
        encoding="utf-8",
    )
    return target


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--public-key", required=True, type=Path)
    parser.add_argument("--clean", action="store_true")
    args = parser.parse_args(argv)
    if args.clean:
        shutil.rmtree(PROJECT_ROOT / "build" / "cython-c", ignore_errors=True)
        for path in (PROJECT_ROOT / "ydcore").glob("*.so"):
            path.unlink()
    generated = embed_public_key(args.public_key)
    extensions = [
        Extension(
            f"ydcore.{name}",
            [str(PROJECT_ROOT / "ydcore" / f"{name}.py")],
            extra_compile_args=["-g0"],
            extra_link_args=["-Wl,--strip-all"],
        )
        for name in CORE_MODULES
    ]
    setup(
        name="ydtrader-protected-core",
        ext_modules=cythonize(
            extensions,
            build_dir=str(PROJECT_ROOT / "build" / "cython-c"),
            compiler_directives={
                "language_level": 3,
                "binding": True,
                "linetrace": False,
                "profile": False,
                "embedsignature": False,
            },
            compile_time_env={"CYTHON_TRACE": False},
            annotate=False,
        ),
        script_args=["build_ext", "--inplace"],
        options={"build_ext": {"force": True}},
    )
    generated.unlink(missing_ok=True)
    missing = [name for name in CORE_MODULES if not list((PROJECT_ROOT / "ydcore").glob(f"{name}.*.so"))]
    if missing:
        raise SystemExit(f"missing Cython outputs: {', '.join(missing)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
